// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import HelloShay from './HelloShay.vue'


// Export components individually
export { HelloShay }

// What should happen if the user installs the library as a plugin
function install(Vue) {
    Vue.component('HelloShay', HelloShay)
}

// Export the library as a plugin
export default { install: install }
